---
title: "ST558 Project 1"
author: "Tao Sun"
date: "`r Sys.Date()`"
output: rmarkdown::github_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# JSON data description
  
  **JSON** (JavaScript Object Notation) is a lightweight and flexible data format that is easy for humans to read and for machines to parse. JSON has become a common format used in: 
  
  * Public APIs (e.g., Twitter)
  * NoSQL databases as a document format (e.g., MongoDB)
  * Relational databases as a new column type (e.g., PostgreSQL)
  
<<<<<<< HEAD
  JSON format is text only and independent to any programming language, so it is a good way to store data. 
  
  [Wikipedia introduction](https://en.wikipedia.org/wiki/JSON) and [JSON syntax introduction](http://json.org/).
  
# Ways to read JSON data into R

  There three major R packages available for reading JSON data into R (rjson, RJSONIO and jsonlite). Examples to compare behavior and performance of those three packages are [here](https://rstudio-pubs-static.s3.amazonaws.com/31702_9c22e3d1a0c44968a4a1f9656f1800ab.html). I prefer jsonlite because it provides more options for manipulating the format and most importantly we can get well formatted data by default.
  
# Access NFL records 'Franchise' API and pulldown JSON data
